### ISSUE TITLE
`Uncaught TypeError: Cannot read property '2' of null`

### ISSUE THREAD

**Issue by macool** [GrowMoi/moi-front-end#4]
http://moi-frontend.herokuapp.com/#/tab/dash

:confounded: 

<img width="533" alt="screen shot 2015-11-21 at 1 45 39 pm" src="https://cloud.githubusercontent.com/assets/1407000/11319911/33e237d0-9056-11e5-8634-95b7050e1070.png">

**Comment by fabricioflores** [comment]
yo tengo un error de q no se encuentra cordova

**Comment by macool** [comment]
córdova nunca se va a encontrar en development. solamente desplegando a móviles. parece que el error del `2` es de mi navegador. tal vez algún plugin

**Comment by fabricioflores** [comment]
pasos para reproducir? yo no tengo ese error...
