### ISSUE TITLE
enlaces no llevan a ningún lado

### ISSUE THREAD

**Issue by macool** [GrowMoi/moi-front-end#43]
en la vista de contenido maximizado

<img width="771" alt="screen shot 2016-04-07 at 11 02 50 am" src="https://cloud.githubusercontent.com/assets/1407000/14363977/5d0b0faa-fccc-11e5-9524-989e81216f53.png">

**Comment by fabricioflores** [comment]
@daosgc revisa por fa este bug. Cuando envíes el PR haz referencia a este bug para que se cierre automáticamente al mergerlo
