### ISSUE TITLE
missing asset

### ISSUE THREAD

**Issue by macool** [GrowMoi/moi-front-end#44]
after deploying to iOS device..

<img width="974" alt="screen shot 2016-04-09 at 8 04 39 am" src="https://cloud.githubusercontent.com/assets/1407000/14403781/d491d06e-fe29-11e5-995c-80ac1a6c0554.png">

**Comment by fabricioflores** [comment]
tenemos varios 404 en las aplicaciones móviles, pero si se siguen mostrando. Voy a cerrar este bug pero si debemos tener en consideración que las rutas estén bien tanto para web como para las apps móviles
