### ISSUE TITLE
Error del servidor en notas al aprender

### ISSUE THREAD

**Issue by fabricioflores** [GrowMoi/moi-front-end#59]
Pasos a reproducir:
- Ir a un contenido
- Aprender sin llenar nada en notas

Aquí se deben considerar varios aspectos.
- Tenemos que controlar que no envíe la nota si el text area está vacío (frontend)
- Tenemos que controlar el siguiente caso: creo una nota, luego no la quiero y borro todo. Eso debería permitirme pero el backend va a dar error por estar en blanco (backend)
@daosgc @macool ^

**Comment by macool** [comment]
estoy de acuerdo, el backend debería permitir "borrar" estas notas

**Comment by daosgc** [comment]
Trabajemos entonces @macool tu en el back y yo en el front mi cholo.. :mono:

**Comment by macool** [comment]
resuelto en #60 cc @daosgc @fabricioflores

**Comment by macool** [comment]
fixed in #60
